### ISSUE TITLE
Compiler warning on CCL

### ISSUE THREAD

**Issue by rpgoldman** [sharplispers/clx#44] opened 2016-08-17 17:37 UTC
This looks like it might be important:

```
;Compiler warnings for "home:lisp;sharplispers-clx;dep-openmcl.lisp.newest" :
;   In XLIB::HOST-ADDRESS: Undefined function CCL::HOST-AS-INET-HOST
```

**Comment by dkochmanski** [comment] 2016-08-18 09:16
Duplicate of #20

**Closed by dkochmanski** 2016-08-18 09:16 UTC
