### ISSUE TITLE
GLX error code 154.3

### ISSUE THREAD

**Issue by malcolmstill** [sharplispers/clx#63] opened 2016-11-15 15:29 UTC
I get the following error when trying to run the gl-test demo:

```
Asynchronous VALUE-ERROR in request 39 (last request was 41)  Code 154.3 [GLX] Value 39.
   [Condition of type VALUE-ERROR]

Restarts:
 0: [CONTINUE] Ignore
 1: [RETRY] Retry SLIME REPL evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "new-repl-thread" RUNNING {1002BB32B3}>)

Backtrace:
  0: (XLIB::READ-ERROR-INPUT #<DISPLAY :0 (Fedora Project R11804000)> 39 #S(XLIB::REPLY-BUFFER :SIZE 32 :IBUF8 #(0 2 39 0 39 0 ...) :NEXT NIL :DATA-SIZE 32) #<SB-THREAD:THREAD "new-repl-thread" RUNNING {10..
  1: (XLIB::READ-INPUT #<DISPLAY :0 (Fedora Project R11804000)> NIL NIL #<FUNCTION (LAMBDA (XLIB::PENDING-COMMAND) :IN XLIB::READ-REPLY) {1004F10D2B}> #S(XLIB::PENDING-COMMAND :SEQUENCE 41 :REPLY-BUFFER NI..
  2: (XLIB::READ-REPLY #<unavailable argument> #<unavailable argument>)
  3: (XLIB/GLX:MAKE-CURRENT #<WINDOW :0 2400002> #<XLIB/GLX::CONTEXT :0 37748741>)
  4: (TEST #<FUNCTION GEARS> :HOST "" :DISPLAY 0 :WIDTH 200 :HEIGHT 200)
```

**Comment by dkochmanski** [comment] 2017-01-30 20:09
gl test demo is known not to work and waits for a person who will fix it :-)

**Comment by dkochmanski** [comment] 2018-01-31 19:35
Duplicate of #3

**Closed by dkochmanski** 2018-01-31 19:35 UTC
